<Project>
  <Import Project="Version.props" />
  <PropertyGroup>
      <Company>Proxima Software</Company>
      <Authors>Proxima Software</Authors>
      <Copyright>Copyright © Proxima Software 2026</Copyright>
      <Product>Proxima.Align</Product>
      <Description>Visual Studio 2026 extension for aligning assignment operators</Description>
 </PropertyGroup>
 
 <ItemGroup>
	<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
	  <_Parameter1>$(AssemblyName).Tests</_Parameter1>
	</AssemblyAttribute>
 </ItemGroup>

    <PropertyGroup>
        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
    </PropertyGroup>

    <Target Name="CopyProjectReferencesToPackage" DependsOnTargets="BuildOnlySettings;ResolveReferences;">
        <ItemGroup>
            <_ReferenceCopyLocalPaths Include="@(ReferenceCopyLocalPaths-&gt;WithMetadataValue('ReferenceSourceTarget', 'ProjectReference')-&gt;WithMetadataValue('PrivateAssets', 'All'))" />
        </ItemGroup>

        <ItemGroup>
            <BuildOutputInPackage Include="@(_ReferenceCopyLocalPaths)" TargetPath="%(_ReferenceCopyLocalPaths.DestinationSubDirectory)" />
        </ItemGroup>
    </Target>

</Project>
